### ISSUE TITLE
generating routes from a directory

### ISSUE THREAD

**Issue by idkjs** [callstack/reroute#12]
Suggestion add option to generate routes from a pages dir. For example, add your routes to a subdir called pages.

Then use Node.fs to read the page name modules and use them to generate your router config.

I messing with this but if you already have something in mind, maybe someone can share it?

This would cut down on re writing your router file everytime you create a page.

**Comment by thangngoc89** [comment]
What you are describing is called code generation? I would say this belong to another project.
