### ISSUE TITLE
How to use Link from child component

### ISSUE THREAD

**Issue by guido4000** [callstack/reroute#13]
I wonder how to use the Link module in a child component.
Is it necessary to define the RouterConfig and Router in every component where the Link module needs to be used?

**Comment by thangngoc89** [comment]
You can access the Link with dot notation from the module you defined it

**Comment by guido4000** [comment]
I am still not sure how to accomplish that. 

I have three files:

1. Router Code
```
module CreateRouter = (Config: RouterConfig) => {
  module Container = {
  ...
  module Link = {
```

2. Main app file
```
module RouterConfig = {
...
module Router = ReRoute.CreateRouter(RouterConfig);
...
  <Router.Link route=Admin>
...
```

3. Route
```<Router.Link route=Admin>
???
  <Router.Link route=Admin>
```

How can I import RouterConfig and Router from the main app file (2) in a route file (3)?

**Comment by guido4000** [comment]
I tried to use it with `<App.Router.Link..`, but this leads to a compiler error:

`ninja: error: dependency cycle: src/app.cmj -> src/admin.cmj -> src/app.cmj`

**Comment by guido4000** [comment]
Extracting RouterConfig and Router into a separate module router.re solved the issue.
Thank you @thangngoc89.
